# Generated by Django 5.2.4 on 2025-08-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='avalability',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='seller',
            field=models.TextField(default='Temu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
