# Generated by Django 5.2.4 on 2025-08-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_productmodel_avalability_productmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(default='Inserte descripción'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(default=1.1),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='seller',
            field=models.TextField(default='Temu'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(default='producto de desconocido', max_length=50),
        ),
    ]
