# Generated by Django 5.2.4 on 2025-08-22 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_productmodel_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='avalability',
            new_name='availability',
        ),
    ]
